'''Testing integrated setup

Copyright (c) 2015 K. Nordstroem <k.nordstroem@helveting.ch>

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.


Very nice indeed

Call with

$ scons tb_test1

to build the tb_test1 testbench. This is the default behaviour and
also works w/o any parameter.

$ scons sim/run

to run the simulation

'''
import logging
#import pdb

logging.basicConfig(level=11)

env = Environment(
    tools=['default', 'cogpy'],
    TB_ENTITY='tb_test1',
    COMPILE_OPTIONS=['+cover=sbceft'],
    SIM_OPTIONS=['-coverage', '-msgmode', 'both', '-displaymsgmode', 'both'],
    MODELSIM='E:\\modeltech_pe_10.4a\\win32pe',
    BASEDIR=['C:\\Users\\kn\\Documents\\workspace\\test1\\tb\\test1\\',
             'C:\\Users\\kn\\Documents\\workspace\\test1\\src'],
    TB_FILE='C:\\Users\\kn\\Documents\\workspace\\test1\\tb\\test1\\tb_test1.sv'
)

simrun = env.cogpy_sim('sim/run.do')
tb = env.cogpy_builder('tb_test1.sv')

Default(tb)
#Default(simrun)
