class cogCompilerInterface(object):
    def getLibsContent(libs):
        # Useful but not necessry
        return {}

    def compileAllFiles():
        # Required to compile list generated by cog.
        raise NotImplementedError
        
    # The following functions are obviously not required, but the
    # simulation and compiler tools usually go hand-in-hand.
    def runSimulation():
        raise NotImplementedError

    def runSimulationGui():
        raise NotImplementedError
