class cogCompilerInterface(object):
    def getLibsContent(libs):
        # Useful but not necessry
        return {}

    def compileAllFiles():
        # Required to compile list generated by cog.
        raise NotImplementedError
